// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cfgagent.proto

package CfgAgent // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CfgError_ECode int32

const (
	CfgError_E_OK                CfgError_ECode = 0
	CfgError_E_INVALID_PARAMETER CfgError_ECode = 752101
	CfgError_E_INNER_TIMEOUT     CfgError_ECode = 752102
	CfgError_E_INNER_ERR         CfgError_ECode = 752103
	CfgError_E_INVALID_DELETE    CfgError_ECode = 752104
	CfgError_E_INVALID_NOT_FIND  CfgError_ECode = 752105
)

var CfgError_ECode_name = map[int32]string{
	0:      "E_OK",
	752101: "E_INVALID_PARAMETER",
	752102: "E_INNER_TIMEOUT",
	752103: "E_INNER_ERR",
	752104: "E_INVALID_DELETE",
	752105: "E_INVALID_NOT_FIND",
}
var CfgError_ECode_value = map[string]int32{
	"E_OK":                0,
	"E_INVALID_PARAMETER": 752101,
	"E_INNER_TIMEOUT":     752102,
	"E_INNER_ERR":         752103,
	"E_INVALID_DELETE":    752104,
	"E_INVALID_NOT_FIND":  752105,
}

func (x CfgError_ECode) String() string {
	return proto.EnumName(CfgError_ECode_name, int32(x))
}
func (CfgError_ECode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cfgagent_d61ba5164df5f047, []int{0, 0}
}

type CfgError struct {
	Code                 CfgError_ECode `protobuf:"varint,1,opt,name=code,proto3,enum=CfgAgent.CfgError_ECode" json:"code,omitempty"`
	Str                  string         `protobuf:"bytes,2,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CfgError) Reset()         { *m = CfgError{} }
func (m *CfgError) String() string { return proto.CompactTextString(m) }
func (*CfgError) ProtoMessage()    {}
func (*CfgError) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfgagent_d61ba5164df5f047, []int{0}
}
func (m *CfgError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CfgError.Unmarshal(m, b)
}
func (m *CfgError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CfgError.Marshal(b, m, deterministic)
}
func (dst *CfgError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CfgError.Merge(dst, src)
}
func (m *CfgError) XXX_Size() int {
	return xxx_messageInfo_CfgError.Size(m)
}
func (m *CfgError) XXX_DiscardUnknown() {
	xxx_messageInfo_CfgError.DiscardUnknown(m)
}

var xxx_messageInfo_CfgError proto.InternalMessageInfo

func (m *CfgError) GetCode() CfgError_ECode {
	if m != nil {
		return m.Code
	}
	return CfgError_E_OK
}

func (m *CfgError) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type GetCfgReq struct {
	App                  string   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCfgReq) Reset()         { *m = GetCfgReq{} }
func (m *GetCfgReq) String() string { return proto.CompactTextString(m) }
func (*GetCfgReq) ProtoMessage()    {}
func (*GetCfgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfgagent_d61ba5164df5f047, []int{1}
}
func (m *GetCfgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCfgReq.Unmarshal(m, b)
}
func (m *GetCfgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCfgReq.Marshal(b, m, deterministic)
}
func (dst *GetCfgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCfgReq.Merge(dst, src)
}
func (m *GetCfgReq) XXX_Size() int {
	return xxx_messageInfo_GetCfgReq.Size(m)
}
func (m *GetCfgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCfgReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCfgReq proto.InternalMessageInfo

func (m *GetCfgReq) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *GetCfgReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfgagent_d61ba5164df5f047, []int{2}
}
func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (dst *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(dst, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetCfgResp struct {
	Version              string      `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Kv                   []*KeyValue `protobuf:"bytes,2,rep,name=kv,proto3" json:"kv,omitempty"`
	Err                  *CfgError   `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCfgResp) Reset()         { *m = GetCfgResp{} }
func (m *GetCfgResp) String() string { return proto.CompactTextString(m) }
func (*GetCfgResp) ProtoMessage()    {}
func (*GetCfgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfgagent_d61ba5164df5f047, []int{3}
}
func (m *GetCfgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCfgResp.Unmarshal(m, b)
}
func (m *GetCfgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCfgResp.Marshal(b, m, deterministic)
}
func (dst *GetCfgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCfgResp.Merge(dst, src)
}
func (m *GetCfgResp) XXX_Size() int {
	return xxx_messageInfo_GetCfgResp.Size(m)
}
func (m *GetCfgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCfgResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCfgResp proto.InternalMessageInfo

func (m *GetCfgResp) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetCfgResp) GetKv() []*KeyValue {
	if m != nil {
		return m.Kv
	}
	return nil
}

func (m *GetCfgResp) GetErr() *CfgError {
	if m != nil {
		return m.Err
	}
	return nil
}

type ApplyCfgReq struct {
	App                  string   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyCfgReq) Reset()         { *m = ApplyCfgReq{} }
func (m *ApplyCfgReq) String() string { return proto.CompactTextString(m) }
func (*ApplyCfgReq) ProtoMessage()    {}
func (*ApplyCfgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfgagent_d61ba5164df5f047, []int{4}
}
func (m *ApplyCfgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyCfgReq.Unmarshal(m, b)
}
func (m *ApplyCfgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyCfgReq.Marshal(b, m, deterministic)
}
func (dst *ApplyCfgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyCfgReq.Merge(dst, src)
}
func (m *ApplyCfgReq) XXX_Size() int {
	return xxx_messageInfo_ApplyCfgReq.Size(m)
}
func (m *ApplyCfgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyCfgReq.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyCfgReq proto.InternalMessageInfo

func (m *ApplyCfgReq) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *ApplyCfgReq) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ApplyCfgReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ApplyCfgReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ApplyCfgResp struct {
	Err                  *CfgError `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ApplyCfgResp) Reset()         { *m = ApplyCfgResp{} }
func (m *ApplyCfgResp) String() string { return proto.CompactTextString(m) }
func (*ApplyCfgResp) ProtoMessage()    {}
func (*ApplyCfgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfgagent_d61ba5164df5f047, []int{5}
}
func (m *ApplyCfgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyCfgResp.Unmarshal(m, b)
}
func (m *ApplyCfgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyCfgResp.Marshal(b, m, deterministic)
}
func (dst *ApplyCfgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyCfgResp.Merge(dst, src)
}
func (m *ApplyCfgResp) XXX_Size() int {
	return xxx_messageInfo_ApplyCfgResp.Size(m)
}
func (m *ApplyCfgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyCfgResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyCfgResp proto.InternalMessageInfo

func (m *ApplyCfgResp) GetErr() *CfgError {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterType((*CfgError)(nil), "CfgAgent.CfgError")
	proto.RegisterType((*GetCfgReq)(nil), "CfgAgent.GetCfgReq")
	proto.RegisterType((*KeyValue)(nil), "CfgAgent.KeyValue")
	proto.RegisterType((*GetCfgResp)(nil), "CfgAgent.GetCfgResp")
	proto.RegisterType((*ApplyCfgReq)(nil), "CfgAgent.ApplyCfgReq")
	proto.RegisterType((*ApplyCfgResp)(nil), "CfgAgent.ApplyCfgResp")
	proto.RegisterEnum("CfgAgent.CfgError_ECode", CfgError_ECode_name, CfgError_ECode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CfgAgentClient is the client API for CfgAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CfgAgentClient interface {
	GetCfg(ctx context.Context, in *GetCfgReq, opts ...grpc.CallOption) (*GetCfgResp, error)
	WatchCfg(ctx context.Context, in *GetCfgReq, opts ...grpc.CallOption) (CfgAgent_WatchCfgClient, error)
	ApplyCfg(ctx context.Context, in *ApplyCfgReq, opts ...grpc.CallOption) (*ApplyCfgResp, error)
}

type cfgAgentClient struct {
	cc *grpc.ClientConn
}

func NewCfgAgentClient(cc *grpc.ClientConn) CfgAgentClient {
	return &cfgAgentClient{cc}
}

func (c *cfgAgentClient) GetCfg(ctx context.Context, in *GetCfgReq, opts ...grpc.CallOption) (*GetCfgResp, error) {
	out := new(GetCfgResp)
	err := c.cc.Invoke(ctx, "/CfgAgent.CfgAgent/GetCfg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cfgAgentClient) WatchCfg(ctx context.Context, in *GetCfgReq, opts ...grpc.CallOption) (CfgAgent_WatchCfgClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CfgAgent_serviceDesc.Streams[0], "/CfgAgent.CfgAgent/WatchCfg", opts...)
	if err != nil {
		return nil, err
	}
	x := &cfgAgentWatchCfgClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CfgAgent_WatchCfgClient interface {
	Recv() (*GetCfgResp, error)
	grpc.ClientStream
}

type cfgAgentWatchCfgClient struct {
	grpc.ClientStream
}

func (x *cfgAgentWatchCfgClient) Recv() (*GetCfgResp, error) {
	m := new(GetCfgResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cfgAgentClient) ApplyCfg(ctx context.Context, in *ApplyCfgReq, opts ...grpc.CallOption) (*ApplyCfgResp, error) {
	out := new(ApplyCfgResp)
	err := c.cc.Invoke(ctx, "/CfgAgent.CfgAgent/ApplyCfg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CfgAgentServer is the server API for CfgAgent service.
type CfgAgentServer interface {
	GetCfg(context.Context, *GetCfgReq) (*GetCfgResp, error)
	WatchCfg(*GetCfgReq, CfgAgent_WatchCfgServer) error
	ApplyCfg(context.Context, *ApplyCfgReq) (*ApplyCfgResp, error)
}

func RegisterCfgAgentServer(s *grpc.Server, srv CfgAgentServer) {
	s.RegisterService(&_CfgAgent_serviceDesc, srv)
}

func _CfgAgent_GetCfg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCfgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CfgAgentServer).GetCfg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CfgAgent.CfgAgent/GetCfg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CfgAgentServer).GetCfg(ctx, req.(*GetCfgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CfgAgent_WatchCfg_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCfgReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CfgAgentServer).WatchCfg(m, &cfgAgentWatchCfgServer{stream})
}

type CfgAgent_WatchCfgServer interface {
	Send(*GetCfgResp) error
	grpc.ServerStream
}

type cfgAgentWatchCfgServer struct {
	grpc.ServerStream
}

func (x *cfgAgentWatchCfgServer) Send(m *GetCfgResp) error {
	return x.ServerStream.SendMsg(m)
}

func _CfgAgent_ApplyCfg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCfgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CfgAgentServer).ApplyCfg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CfgAgent.CfgAgent/ApplyCfg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CfgAgentServer).ApplyCfg(ctx, req.(*ApplyCfgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CfgAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CfgAgent.CfgAgent",
	HandlerType: (*CfgAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCfg",
			Handler:    _CfgAgent_GetCfg_Handler,
		},
		{
			MethodName: "ApplyCfg",
			Handler:    _CfgAgent_ApplyCfg_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchCfg",
			Handler:       _CfgAgent_WatchCfg_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cfgagent.proto",
}

func init() { proto.RegisterFile("cfgagent.proto", fileDescriptor_cfgagent_d61ba5164df5f047) }

var fileDescriptor_cfgagent_d61ba5164df5f047 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0xe3, 0xb4, 0x38, 0x37, 0x55, 0x31, 0xb7, 0x0f, 0x99, 0x88, 0x45, 0x34, 0x62, 0x91,
	0x05, 0xb6, 0x50, 0x80, 0x05, 0xca, 0xca, 0x24, 0x03, 0x8a, 0xda, 0x26, 0x68, 0x64, 0x8a, 0xc4,
	0xc6, 0x32, 0xe9, 0x24, 0x45, 0x29, 0xf1, 0x30, 0x63, 0x22, 0xe5, 0x0f, 0xf8, 0x25, 0x3e, 0x84,
	0x4f, 0xe0, 0xb5, 0xf6, 0x0f, 0xa0, 0x71, 0x3c, 0x75, 0xc3, 0x4b, 0xea, 0x6e, 0xee, 0xbd, 0xe7,
	0xf8, 0x9e, 0x73, 0xc6, 0x03, 0x7b, 0x93, 0xe9, 0x2c, 0x99, 0xf1, 0x45, 0x16, 0x08, 0x99, 0x66,
	0x29, 0x3a, 0xfd, 0xe9, 0x2c, 0xd4, 0x35, 0xf9, 0x62, 0x81, 0x2e, 0xa8, 0x94, 0xa9, 0xc4, 0x07,
	0x50, 0x9f, 0xa4, 0xe7, 0xdc, 0xb3, 0xda, 0x56, 0x67, 0xaf, 0xeb, 0x05, 0x06, 0x15, 0x18, 0x44,
	0x40, 0xfb, 0xe9, 0x39, 0x67, 0x05, 0x0a, 0x5d, 0xb0, 0x55, 0x26, 0xbd, 0x5a, 0xdb, 0xea, 0x34,
	0x98, 0x3e, 0x92, 0x4f, 0x16, 0x6c, 0x17, 0x08, 0x74, 0xa0, 0x4e, 0xe3, 0xf1, 0xb1, 0xbb, 0x85,
	0x77, 0x61, 0x9f, 0xc6, 0xc3, 0xd1, 0x59, 0x78, 0x32, 0x1c, 0xc4, 0x2f, 0x43, 0x16, 0x9e, 0xd2,
	0x88, 0x32, 0xf7, 0x6b, 0xee, 0xe3, 0x21, 0xdc, 0xd6, 0xa3, 0x11, 0x65, 0x71, 0x34, 0x3c, 0xa5,
	0xe3, 0x57, 0x91, 0xfb, 0x2d, 0xf7, 0xf1, 0x0e, 0x34, 0x4d, 0x9b, 0x32, 0xe6, 0x7e, 0xcf, 0x7d,
	0x3c, 0x02, 0xb7, 0xfa, 0xc8, 0x80, 0x9e, 0xd0, 0x88, 0xba, 0x3f, 0x72, 0x1f, 0x3d, 0xc0, 0xaa,
	0x3f, 0x1a, 0x47, 0xf1, 0xf3, 0xe1, 0x68, 0xe0, 0xfe, 0xcc, 0x7d, 0xd2, 0x83, 0xc6, 0x0b, 0x9e,
	0xf5, 0xa7, 0x33, 0xc6, 0x3f, 0x68, 0xa5, 0x89, 0x10, 0x85, 0xad, 0x06, 0xd3, 0x47, 0xbc, 0x07,
	0x8d, 0x45, 0xf2, 0x9e, 0x2b, 0x91, 0x4c, 0x78, 0xe9, 0xa0, 0x6a, 0x90, 0x2e, 0x38, 0xc7, 0x7c,
	0x75, 0x96, 0x5c, 0x7e, 0x2c, 0x5c, 0xce, 0xf9, 0xca, 0x70, 0xe7, 0x7c, 0x85, 0x07, 0xb0, 0xbd,
	0xd4, 0xa3, 0x92, 0xb7, 0x2e, 0x88, 0x00, 0x30, 0x0b, 0x95, 0x40, 0x0f, 0x6e, 0x2d, 0xb9, 0x54,
	0xef, 0xd2, 0x45, 0xc9, 0x34, 0x25, 0x12, 0xa8, 0xcd, 0x97, 0x5e, 0xad, 0x6d, 0x77, 0x9a, 0x5d,
	0xac, 0x12, 0x36, 0xfb, 0x58, 0x6d, 0xbe, 0xc4, 0xfb, 0x60, 0x73, 0x29, 0x3d, 0xbb, 0x6d, 0x6d,
	0x82, 0xcc, 0x35, 0x30, 0x3d, 0x26, 0x0a, 0x9a, 0xa1, 0x10, 0x97, 0xab, 0x7f, 0x9a, 0x6c, 0x81,
	0x73, 0x91, 0xaa, 0x4c, 0xfb, 0x2a, 0xb5, 0x5e, 0xd5, 0x9b, 0x01, 0xd8, 0xbf, 0x05, 0x70, 0x5d,
	0x7e, 0x7d, 0x43, 0x3e, 0x79, 0x0c, 0xbb, 0xd5, 0x52, 0x25, 0x8c, 0x54, 0xeb, 0xbf, 0x52, 0xbb,
	0x9f, 0xd7, 0x7f, 0x59, 0x31, 0xc2, 0x27, 0xb0, 0xb3, 0x4e, 0x0a, 0xf7, 0x2b, 0xfc, 0xd5, 0x65,
	0xb5, 0x0e, 0xfe, 0x6c, 0x2a, 0x41, 0xb6, 0xf0, 0x29, 0x38, 0xaf, 0x93, 0x6c, 0x72, 0x71, 0x53,
	0xe2, 0x43, 0x0b, 0x7b, 0xe0, 0x18, 0xd1, 0x78, 0x58, 0xa1, 0xae, 0xa5, 0xd7, 0x3a, 0xfa, 0x5b,
	0x5b, 0xd3, 0x9f, 0xed, 0xbe, 0x81, 0xa0, 0x67, 0x86, 0x6f, 0x77, 0x8a, 0x07, 0xf4, 0xe8, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x84, 0x98, 0xc3, 0x52, 0x03, 0x00, 0x00,
}
